-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost
-- Tiempo de generación: 24-11-2018 a las 00:54:05
-- Versión del servidor: 10.1.36-MariaDB
-- Versión de PHP: 7.2.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `CandyBoy`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `products`
--

CREATE TABLE `products` (
  `SKU` varchar(30) CHARACTER SET latin1 NOT NULL,
  `title` text CHARACTER SET latin1,
  `categorie` text CHARACTER SET latin1,
  `content` text CHARACTER SET latin1,
  `caducity` date NOT NULL,
  `price` double NOT NULL,
  `ingredients` text CHARACTER SET latin1,
  `nutritional_information` text CHARACTER SET latin1,
  `image_path` text CHARACTER SET latin1,
  `description` text CHARACTER SET latin1 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Volcado de datos para la tabla `products`
--

INSERT INTO `products` (`SKU`, `title`, `categorie`, `content`, `caducity`, `price`, `ingredients`, `nutritional_information`, `image_path`, `description`) VALUES
(' BE070847030331', 'Monster Muscle Vainilla | USA ', 'soda', '444 ml.', '2019-12-20', 129.87, 'agua, proteína concentrada de LECHE, caseinato cálcico (LECHE), CREMA, azúcar, glucosa, taurina, celulosa microcristalina, citrato sódico, citrato potásico, sal, goma celulosa, cafeína, aromas naturales, vitamina C, goma gellan, aromas naturales, sucralosa, vitamina B3, acesulfamo K, inositol, L-carnitina tartrato, vitaminas (B6, B2).\r\n', '42.8 kcal, Grasas: 0.9g, Saturadas: 0.6g, Carbohidratos: 2.2g, Azúcares: 2g, Proteínas: 6g & Sal: 0g\r\n', 'prd-monster-vainilla-protein.jpg', 'Nueva Monster pensada para el Post-entrenamiento. Proteína + Carbohidratos + Energía !! ¡Una súper deliciosa bebida de vainilla! Sin Gluten.\r\n'),
(' BE110160', 'Bebida de Té Verde y Bayas de Goji', 'te', '250 ml.', '2019-07-31', 45.28, 'agua, zumo de fruta (9% manzana y mandarina concentrada, y 1% goji), infusión de té verde, regulador de acidez: ácido cítrico, aromatizante natural, colorante natural (cártamo y limón).\r\n', '30 kcal •Grasas: <0,1g • Carbohidratos: 6,7g - Azúcares: 6,4g • Proteínas: 0,1g • Sal: 0,1g\r\n', 'te-verde-mangajo-goji.png', 'Bebida de Té verde elaborada con agua de manantial y bayas de Goji. Con antioxidantes naturales y beta-caroteno.\r\nOriginarias del Himalaya, las bayas de Goji son una de las fuentes más ricas en beta-caroteno y antioxidantes. Dos de las fuentes de antioxidantes más conocidas, se unen para obtener una bebida desintoxicante de excelente sabor.\r\n'),
(' BE112168', 'Licor Coreano Soju Chum Churum Melocot&oacuten Rosado', 'liqueur', '14º 360 ml.', '2019-01-08', 187.32, 'alcohol, jarabe de azúcar isomerizado, estevia glucosilada enzimáticamente modificada, ácido cítrico, melocotón concentrado, aroma de melocotón, agua.\r\n', '_', 'prd-bebida-coreana-chamisul-chum-churum-soju-peach.png', 'Licor coreano Soju 100% puro y natural elaborado con agua mineral, arroz en grano, cebada, caña de azúcar, fructosa cristalina y melocotón rosado (mom). Chum Churum es de paladar muy suave y refrescante.\r\nOfrece notas lácteas y de anís. Su contenido de alcohol moderado hace que sea agradable como un aperitivo, o como cóctel en lugar de ginebra o vodka.\r\n'),
(' BE22355A', 'Cerveza Coreana MAX Cream ', 'liqueur', '355 ml. 4,5º', '2019-03-25', 36.1, 'MALTA.', '_', 'prd-cerveza-max-beer-cream.png', 'Las burbujas y el rico y duradero sabor de la malta son parte del auténtico sabor desarrollado en base a 12 años de conocimiento. El exclusivo proceso tecnológico \"no-termal\" hace que Max tenga un sabor más fresco y suave. Ahora puedes disfrutar cerveza cremosa y fresca en casa. Como la primera cerveza de malta auténtica de Corea, Max contiene Malta Especial y un 20% más de aroma de lúpulo para un rico sabor.\r\n'),
(' BE780108', 'Cerveza Japonesa Uijin Yuzu Blond ', 'liqueur', '330 ml. 6,5º', '2019-08-31', 96.5, 'Agua, MALTA de CEBADA, lúpulo, azúcar, yuzu, levadura. \r\n_', '–', 'prd-cerveza-japonesa-uijin-yuzu-blond-japonesa.png', 'Cerveza diseñada por el famoso cervecero japonés Ryohei Sugawara. Su sabor amargo de Yuzu y el atractivo aroma del lúpulo hacen que Uijin Beer destaque en su clase. Su aroma fresco y afrutado tiene una nota dominante de moscatel.\r\n'),
(' BE921010', 'Licor Coreano Soju Chamisul con Pomelo | Grapefruit', 'liqueur', '360 ml. 16º\r\n', '2019-03-19', 170.06, 'agua, alcohol, aroma a pomelo, ácido cítrico, regulador de acidez (E270, E296), sacarosa, jarabe de maíz con alta fructosa.\r\n', '_', 'prd-bebida-coreana-chamisul-jinro-soju-pomelo-grape-fruit.png', 'Descripción: Licor coreano Soju 100% puro y natural elaborado con arroz, cebada, caña de azúcar, fructosa cristalina y zumo de pomelo. Refinado y filtrado 7 veces con carbón de bambú, para obtener un paladar mucho más refrescante.'),
('ALCO8432', 'Miso Coreano Fresco', 'miso', '500 gr.', '2019-12-20', 44.28, 'SOJA (37%), harina de TRIGO, sal, agua, alcohol, Aspergillus oryzae (Koji).  \r\n', '154kcal • Grasas: 1,7g - Saturadas: 0,4g • Carbohidratos: 22g - Azúcares: 11g • Proteínas: 11g • Sal: 9,8g.\r\n', 'prd-miso-japones-coreano.png', 'Miso coreano elaborado con grano de soja tierno, trigo y koji. Mantiene su sabor profundo y fermentación activa. \r\nSu sabor es diferente al miso japonés, por lo que se recomienda no utilizar como sustituto de este. Indicado para recetas coreanas.\r\n'),
('ALSA413', 'Miso Blanco Intenso', 'miso', '300 gr.\r\n', '2020-04-30', 113.07, 'SOJA, malta de arroz (koji), sal, alcohol, colorante E101.\r\n', '187 kcal, Grasas: 6.4g, Saturadas: 1g, Carbohidratos: 20.4g, Azúcares: 16.5g, Proteínas: 11.9g & Sal: 12g\r\n', 'prd-miso-blanco-japones.png', 'El miso blanco o shiro Miso se deja fermentar un año, por lo que su sabor es más suave que el miso rojo.\r\nEl miso es una  pasta aromatizante fermentada y muy sabrosa, hecha con semillas de soja y/o cereales y sal marina. El Miso Blanco o Shiro Miso se deja fermentar durante un año, por lo que su sabor es más suave que el Miso Rojo.\r\nDurante siglos fue considerado un alimento curativo en Japón.\r\nContiene enzimas que ayudan a la digestión, y suministra carbohidratos, lípidos, vitaminas, minerales y proteínas. Algunos sostienen que el miso sin pasteurizar puede reconstruir la flora intestinal que haya sido deteriorada por dietas de alto contenido en carnes, azúcar, productos químicos y antibióticos.\r\n\r\n'),
('ALSA422', 'Miso Blanco con Crema de Arroz', 'miso', '500 gr.', '2019-08-31', 98.77, 'SOJA, arroz, sal, alcohol.\r\n', '203 kcal • Grasas: 5g - Saturadas: 1,62g • Carbohidratos: 29,4g - Azúcares: 22,9g • Proteínas: 10g • Sal: 0,01g.\r\n', 'prd-miso-japones-blanco-arroz.png', 'Miso Blanco mezclado con crema de arroz fermentado. De textura muy cremosa y de sabor intenso.\r\nEl miso (??) es una pasta aromatizante fermentada y muy sabrosa, hecha con semillas de soja y/o cereales y sal marina. El Miso Blanco o Shiro Miso se deja fermentar durante un año, por lo que su sabor es más suave que el Miso Rojo.\r\nDurante siglos fue considerado un alimento curativo en Japón.\r\nContiene enzimas que ayudan a la digestión, y suministra carbohidratos, lípidos, vitaminas, minerales y proteínas. Algunos sostienen que el miso sin pasteurizar puede reconstruir la flora intestinal que haya sido deteriorada por dietas de alto contenido en carnes, azúcar, productos químicos y antibióticos.\r\n'),
('BE203170', 'Espresso Milk Tea U Love It, Taro', 'te', '80 grs. 150 ml.', '2019-03-30', 45.28, 'PAQUETE DE TÉ EN POLVO: azúcar, crema no láctea (jarabe de glucosa, aceite de coco hidrogenado, emulsionante (caseinato de sodio)), LECHE, fosfato ácido dipotásico, antiaglutinante (óxido de silicio E551), maltodextrina, LECHE en polvo, té negro en polvo, saborizante de taro. PAQUETE DE PERLA DE TAPIOCA:  agua, jarabe de malta, almidón de yuca, aceite de girasol, hierba, espesante (goma guar), antiaglutinante (silicato de calcio E552).\r\n', '436 kcal (12%) • Grasas: 12g (17%) • Saturadas 11.9g (60%) • Carbohidratos: 77.8g (29%) • Azúcares 54.3g (60%) • Proteínas: 2.4g (5%) •  Sal: 0,4g (7%).\r\n', 'te_leche_taro.png', 'Disfruta de la excelente combinación del té con leche cremosa, dulce de taro (boniato japonés) y perlas de gelatina con sabor a frutas.\r\n'),
('BE2500300080859', 'Soda Star Wars Space Punch Stormtrooper | Edición Coleccionista', 'soda', '355 ml.', '2019-10-12', 74.53, 'agua, zumo de manzana concentrado, ácido carbónico, zumo de naranja concentrado, ácido cítrico, aromas, edulcorantes (ciclamato de sodio, sucralosa), mezcla de vitaminas (B3, B5, B6, B1, B12), harina de semilla de algarrobo, colorante (antocianinas).\r\n', '5 kcal, Grasas: 0g, Saturadas: 0g, Carbohidratos: 1g, Azúcares: 1g, Proteínas: 0g & Sal: 0g\r\n', 'prd-bebida-star-wars-punch-stormtrooper.png', 'STAR WARS Space Punch. Refresco funcional con sabor a ponche de frutas, enriquecida con vitaminas para ¡que la fuerza te acompañe! Lata coleccionable de Star Wars, disfruta de su refrescante sabor y hazte con toda la colección.'),
('BE4514603363715', 'Café Latte Clear | Transparente ZERO Azúcar ZERO Cafeína', 'soda', ' 600 ml.', '2019-03-29', 67.53, 'agua mineral natural, azúcar (glucosa, fructosa), suero de LECHE, sal, café, aromas, acidulante.\r\n', '10 kcal, Grasas: 0g, Saturadas: 0g, Carbohidratos: 0g, Azúcares: 0g, Proteínas: 2.5g & Sal: 0g\r\n', 'prd-cafe-clear-latte.png', 'Bebida japonesa transparente de Café Espresso con leche, sin cafeína, sin azúcares. Disfruta de todo el sabor de un Café Latte sin complicaciones.'),
('BE4710095938305', 'Postre Bebida Habas Mung y Gelatina Coco | Zenzai ', 'soda', '330 ml.', '2019-01-11', 22.36, 'agua, judías mungo, azúcar, gelatina de coco.\r\n', '80 kcal, Grasas: 0.3g, Saturadas: 0g, Carbohidratos: 16.2g, Azúcares: 8.6g, Proteínas: 3.1g & Sal: 0g\r\n', 'prd-bebida-leche-azuki-ung.jpg', 'Imagínate una deliciosa postre-bebida de habas de soja verde (mung) dulce con azúcar y toppings de gelatina de coco. Disfrútala fría o caliente y si lo deseas agregándole un kiri Mochi tostado, con una una bola de helado o con trocitos de fruta variada (fresas, plátano o manzana).\r\nVuelca el contenido en un bol pequeño o taza grande y a disfrutar!\r\n'),
('BE4712966541133', 'Agua Soda Sabor Ramune | Edición Open Cute ', 'soda', '330 ml.', '2020-05-24', 48.56, 'agua carbonatada, fructosa, azúcar, aroma a soda ramune, regulador de la acidez E330.\r\n', '40.4 kcal, Grasas: 0g, Saturadas: 0g, Carbohidratos: 10.1g, Azúcares: 9.6g, Proteínas: 0g & Sal: 0g\r\n', 'prd-ocean-bomb-ramune.png', 'Agua de soda con gas Pokemon con sabor a ramune. Muy refrescante y realmente única.\r\n'),
('BE540099', 'Agua Soda Sabor Ramune | Edición Pokemon ', 'soda', '330 ml.', '2020-04-16', 58.5, 'Agua carbonatada (99%), concentrado de material de aguas profundas, fructosa, azúcar, sabor de sidra (0.0014%), ácido cítrico.\r\n', '43kcal • Grasas: 0g • Carbohidratos: 10,7g - Azúcares: 10,3g • Proteínas: 0g • Sal: 0,03g.\r\n', 'prd-ocean-bomb-pokemon-cider.png', 'Agua de soda con gas Pokemon con sabor a ramune. Muy refrescante y realmente única.\r\n'),
('BE540211', 'Bebida de Zumo de Uva | Kanahei\'s Small Animals', 'soda', '320 ml.', '2019-06-03', 62.11, 'agua carbonatada, azúcar, zumo concentrado de uva blanca (2,25%), regulador de acidez (E330), aromas, emulsionante (E446), vitamina C.\r\n', '35 kcal, Grasas: 0g, Saturadas: 0g, Carbohidratos: 8.8g, Azúcares: 8.3g, Proteínas: 0g & Sal: 0g\r\n', 'prd-ocean-bomb-kanehei-white-grape.png', ' Increíble bebida sin gas elaborada con agua de primavera y zumo de uva mosto. La bebida de Kanahei\'s Small animals, \"Piske & Usagi\". Realmente adorable.\r\n'),
('BE540433', 'Té Verde Japonés Matcha Latte | La Liga de la Justicia | Aquaman', 'soda', '210 ml.', '2019-01-11', 50.82, 'agua, azúcar, LECHE entera en polvo, LECHE desnatada en polvo, té verde matcha  en polvo, emulsionantes (E473, E407, E466), aromas, agente leudante E500, sal.\r\n', '42.9 kcal, Grasas: 0.9g, Saturadas: 0.6g, Carbohidratos: 7.3g, Azúcares: 5.8g, Proteínas: 1.4g & Sal: 0g\r\n', 'prd-cafe-ocean-bomb-justice-league-matcha-latte.png', 'La marca Ocean Bomb de Taiwan nos trae esta colección de bebidas de Café de “La Liga de La Justicia\". Disfruta del Té Verde Japonés Matcha Latte con Aquaman.\r\n'),
('BE559077', 'Té Negro Latte Batida | Premium', 'te', '200 ml.', '2019-02-01', 64.84, 'agua, LECHE entera en polvo 4%, jarabe de maíz de alta fructosa, azúcar, té negro en polvo 1%, sal, vitamina E, estabilizante (E500), antioxidante (E316), extracto de algas marinas, alfa-ciclodextrina, emulsionante (E471, E451), aromatizante.\r\n', '43 kcal • Grasas: 1,1g - Saturadas: 1,1g • Carbohidratos: 7,3g - Azúcares: 4,9g• Proteínas: 0,9g • Sal: 0,14g\r\n', 'prd-te-negro-latte-japones.png', 'Exquisito Té negro cultivado en Kenia, combinado con crema vaporizada de leche batida. Descubre su sabor intenso y textura aterciopelada.\r\n'),
('BE593583', 'Bebida de Té Negro con limon', 'te', '500 ml.', '2019-05-11', 45.28, 'agua, jarabe de maíz de alta fructosa, té negro, aroma, jarabe de fructosa, concentrado de zumo de limón, vitamina C, reguladores de la acidez (E330, E331, E296), stevia.', '33 kcal • Grasas: 0g - Saturadas: 0g • Carbohidratos: 8g - Azúcares: 1g • Proteínas: 0g • Fibras: 0g • Sal: 0,0225g.\r\n', 'prd-bebida-te-verde-japon-te-negro-limon.png', ' Refrescante bebida de té negro y zumo de limón. \r\n'),
('BE680043', 'Cerveza Duff | Estilo Lager', 'liqueur', ' 333 ml. 4,9º', '2019-06-14', 74.7, 'agua, malta de CEBADA, LÚPULO.\r\n', '_', 'prd-cerveza-duff-simpsons.png', 'Disfruta de la cerveza Duff , inspirada en la mítica serie de Los Simpsons y la favorita de Homer. Tipo lager de Origen Alemán, elaborada bajo la ley de la Pureza Alemana de 1516.\r\nDe color amarillo pálido, espuma blanca con sabor a malta dulce, acabado un poco seco, suave.\r\n'),
('BE780092', 'Cerveza Japonesa Uijin', 'liqueur', '330 ml. 6º', '2020-02-28', 96.5, 'agua, malta de CEBADA, MALTA de TRIGO, lúpulo, azúcar, levadura.\r\n', '_', 'prd-cerveza-japonesa-uijin-blond-japonesa.png', 'Cerveza diseñada por el famoso cervecero japonés Ryohei Sugawara. Su sabor amargo y el atractivo aroma del lúpulo hacen que Uijin Beer destaque en su clase. Su aroma fresco y afrutado tiene una nota dominante de moscatel.\r\n'),
('BE932115', 'Bebida Hidromiel Valhalla Freyja ', 'liqueur', '330 ml. 11º.\r\n', '2019-09-02', 112.39, 'agua, miel, levadura.', '_', 'prd-hidromiel-valhalla-freyja.png', 'Inspirada en Freyja una de la diosas mayores de la mitología nórdica y germánica, diosa del Amor, la Belleza y la Fertilidad. La larga maceración de este Hidromiel con frutos rojos del bosque da como resultado su atractivo color rosado intenso, y su proceso de filtrado en varias fases le otorga un aspecto cristalino. Aromas a frutos rojos tipo grosella y cereza. Dulzor equilibrado por la acidez de las frutas del bosque maceradas que proporciona un paso ligero y fresco pero con un agradable y duradero final. Este hidromiel es ideal para tomar frío como un vino rosado, acompañando una comida ligera, como patés, quesos suaves, pescados a la plancha, pasta. También se puede tomar sola, como preámbulo de una velada romántica.\r\n'),
('BE951941', 'Té de Jazmín con Melocotón Rosado (Momo) | My Secret Garden |', 'te', ' 550 ml.', '2019-05-03', 35.26, 'agua, azúcar, té de jazmín, zumo de melocotón, aromas, aditivos (antioxidante E300, E316, acidulante E331, antiaglomerante E500).\r\n', ' 37,2 kcal • Grasas: 0g • Carbohidratos: 9,2g • Proteínas: 0g • Sal: 0,04g.\r\n', 'prd-te-jazmin-melocoton.png', 'Té de jazmín ligeramente azucarado y con zumo de melocotón rosado japonés (Momo), elaborado con los brotes más tiernos de la flor de jazmín. Las hojas de té son cosechadas en primavera y almacenadas hasta el verano, momento en el que las flores de jazmín están floreciendo. Las flores de jazmín son recolectadas el día en el que sus pétalos mas pequeños y tiernos están bien cerrados. Se mantiene las flores en refrigeración hasta llegada la noche y se mezcla posteriormente con el té.En cuatro horas el té absorbe la fragancia de los capullos de jazmín abiertos; este procedimiento se repite seis o siete veces más.'),
('BED203', 'Cerveza Hitachino Nest Espresso Stout (Estilo Café)', 'liqueur', '330 ml. 7,0º.', '2019-04-28', 119.2, 'agua, MALTA, TRIGO, lúpulo, granos de café.\r\n', '_', 'prd-cerveza-hitachino-espresso-stout-japonesa-coedo-shiro.png', 'La cervecera japonesa dota a su cerveza artesana Hitachino Nest Espresso Stout de una carbonatación tirando a alta. Gracias a los granos de café, su color es similiar al del chocolate oscuro, muy negro, lo que ya indica la profundidad de su sabor y la intensidad de su aroma. Además del potente sabor a café por los granos involucrados en su fabricación, a ello hay que añadirle la presencia de cvainilla, frutas y chocolate negro, que completan el complejo sabor de esta cerveza negra. Por sus características, no se recomienda tomarla muy fría, más bien a 15º para poder sentir y notar las notas de su sabor. Contiene gluten y se recomienda degustar esta cerveza artesana en un vaso English Pint o en un Shaker.'),
('BED22471A', 'Soda de Manzana Verde con 3% de Alcohol', 'liqueur', '355 ml', '2019-08-29', 57.9, 'agua, sirope de maíz de alta fructosa, alcohol, dióxido de carbono, ácido cítrico, manzana concentrada, aroma a manzana. \r\n', '42.8 kcal, Grasas: 0.9g, Saturadas: 0.6g, Carbohidratos: 2.2g, Azúcares: 2g, Proteínas: 6g & Sal: 0g\r\n', 'prd-fanta-soda-lotte-clear-manzana-verde.png', 'Bebida coreana con gas con zumo de de manzana verde, refrescante muy aromatizada y con solo un 3% de alcohol.\r\n'),
('BED6921168558018', 'Té Verde Nongfu Spring', 'te', '500 ml.', '2019-05-13', 37.54, ' agua, té verde en polvo, agente leudante E500.\r\n', '0 kcal, Grasas: 0g, Saturadas: 0g, Carbohidratos: 0g, Azúcares: 0g, Proteínas: 0g & Sal: 0g', 'prd-te-verde-nongfu-spring.png', 'Auténtico Té Verde de hoja tierna, infusionado en crudo, con agua de manantial y sin azúcar.'),
('BED8428259102702', 'Botella de Fuego Valyrio Licor', 'liqueur', '70 cl. 33º.\r\n', '2020-08-23', 361.02, '_', '_', 'prd-fuego-valyrio.png', 'Fuego Valyrio es la bebida que brilla y que esta inspirada en una famosa serie de ficción, el auténtico fuego de los dragones preparado por alquimistas. Una bebida destinada a ser tu mejor acompañante en las fiestas, especial para chupitos. Su sabor recuerda al whisky con canela picante.  Cuenta con 33º de graduación alcohólica y es un licor con el que sentirás el fuego en tu garganta pero con un sabor final ideal. Es el elemento ideal para chupitos ( shots ) o para mezclar con refresco de naranja. El efecto brillante del licor permanece en el tiempo sin problema, solo hace falta agitarla de nuevo para que se desate.  Sin duda un producto que ningún amante de la fiesta y menos un fan de la ficción, puede dejar pasar. Fuego Valyrio Real !!!'),
('DU015162', 'Cortezas de Cerdo 3 Frituras | Mr. Porcky', 'snack', ' 55 grs', '2019-05-05', 68.09, 'corteza de cerdo, sal, potenciador del sabor (E621), proteína de SOJA hidrolizada, bizcocho tostado (harina de TRIGO, carbonato cálcico, hierro, niacina, tiamina, sal), dextrosa, colorante (extracto de paprika, caramelo).\r\n', '615 kcal, Grasas: 46.2g, Saturadas: 16.4g, Carbohidratos: 0.2g, Azúcares: 0.1g, Proteínas: 49.7g & Sal: 3g\r\n', 'prd-snack-mr-porcky-crackels.png', 'La receta tradicional de cortezas de cerdo de Mr.Porky es mítica. Su secreto consiste en freír tres veces a diferente temperatura las cortezas y añadir un especiado único.\r\n'),
('DU053527', 'Sticks de Barquillo de Oreo rellenos de Chocolate | Edición Line Friends', 'snack', '45 grs', '2019-05-05', 45.16, 'azúcar, harina de TRIGO, aceite de palma, cacao en polvo, jarabe de maíz de alta fructosa, almidón, maltodextrina, glucosa, sal, lecitina de SOJA, aromas.\r\n', '488kcal •Grasas: 21,2g - Saturadas: 9,2g • Carbohidratos: 67,4g - Azúcares: 33g. • Proteínas: 4,5g • Sal: 0,2g.\r\n', 'prd-barquillos-oreo.png', 'Deliciosos y sabrosos sticks de barquillo de galletas Oreo, con un interior recubierto de chocolate. Edición Line Friends.\r\n'),
('DU111403', 'Taiyaki de Barquillo y Mousse de Fresa', 'snack', '16.5 grs', '2019-05-31', 38.35, 'Fresa: CHOCOLATE: azúcar, LECHE entera en polvo, aceite de palma, manteca de cacao, fresa deshidratada, LACTOSA, emulsionante (SOJA). OBLEA: harina de TRIGO, almidón, azúcar, harina de maíz, aceite de palma, sal, calcio de MARISCO, emulsionante (SOJA), colorantes (akabito, levadura roja), agente leudante.\r\n', '539 kcal • Grasas: 29,7g • Carbohidratos: 63,6g • Proteínas: 3,6g •  Sal: 0,6g\r\n', 'prd-taiyaki-fresa-meito.png', 'Taiyaki de galleta de barquillo monaka de fresa y relleno de un delicado mousse con suaves y cremosas burbujas de chocolate blanco con fresa.\r\n'),
('DU779134', 'Gominolas Forma Pikachu Sabor Uva', 'snack', '28 grs', '2018-12-31', 42.89, ' jarabe, azúcar, gelatina, zumo de uva concentrado, aceites de palma, sorbitol, acidulante, pectina, aromas, colorantes (cártamo, gardenia), cera.\r\n', '321kcal •Grasas: 0g • Carbohidratos: 77g • Proteínas: 5,4g • Sal: 0,14g.\r\n', 'prd-gominolas-pokemon-pikachu.png', 'Descubre las divertidas gominolas con forma de Pikachu y con sabor a Uva!! Deliciosas y refrescantes! Hay dos diseños aleatorios.\r\n'),
('DU781371', 'Bocaditos Pretz Sabor Miel y Sriracha | Family Size', 'snack', '178 grs', '2018-11-30', 88.28, 'harina de TRIGO, aceite vegetal (semilla de palma, palma, hidrogenado de palma, hidrogenado de semilla de palma), SUERO, maltodextrina, almidón de maíz modificado, contiene el 2% o menos de: sal, levadura (bicarbonato sódico, pirofosfato ácido de sodio), dextrosa, lecitina de SOJA, azúcar moreno, azúcar, ajo en polvo, pimienta roja cayena, tomate en polvo, vinagres sólidos, ácido cítrico, especias, extracto de levadura, extracto de especias, extracto de paprika, aromas naturales.\r\n', '464kcal • Grasas: 17,9g - Saturadas: 10,7g • Carbohidratos: 71,4g - Azúcares: 10,7g • Proteínas: 7,1g • Sal: 2,61g.\r\n', 'prd-combos-honey-sriracha.png', 'Deliciosos bocaditos de Pretz elaborados con miel y rellenos de crema de salsa Sriracha picante.\r\n'),
('DU884620', 'Galletas Snack Shin Chan Sabor Helado de Vainilla | Edit. Limitada\r\n', 'snack', '25 grs', '2019-02-24', 76.03, 'Azúcar, sémola de maíz, aceites vegetales, margarina, sal de Okinawa, dextrina, yema de HUEVO en polvo, LECHE, crema con aroma a vainilla, sorbitol, aromas, calcio de cáscara de HUEVO, emulsionante, edulcorante, carbonato de calcio. Contiene: TRIGO, SOJA.\r\n', '541 kcal, Grasas: 30.8g, Saturadas: 0g, Carbohidratos: 63.6g, Azúcares: 0g, Proteínas: 2.4g & Sal: 1g\r\n', 'prd-galletas-shin-chan-chocobi-vainilla.png', 'Disfruta de las populares y deliciosas \"galletas\" snack de trigo de Shin Chan con sabor a helado de vainilla. Edición Limitada.\r\n'),
('DUJML2698', 'Snack Lovely Tohato Sabor Helado Menta Chocolate \r\n', 'snack', '77 grs', '2019-02-02', 68.24, 'sémola de maíz blanco, azúcar, aceite vegetal, margarina, LECHE en polvo edulcorada, sal, semilla de cacao, proteína hidrolizada, sorbitol, aromas, emulsionante, colorante E165. Contiene TRIGO, SOJA.', '549 kcal, Grasas: 31.9g, Saturadas: 0g, Carbohidratos: 62.9g, Azúcares: 0g, Proteínas: 2.3g & Sal: 1g\r\n', 'prd-snack-japones-caramel-corn-helado-menta-chocolate-tohato.png', 'Delicioso y crujiente snack de maíz horneado con sabor a refrescante helado de menta con toppings de chocolate.\r\n'),
('DUJML2798', 'Snack Pikachu Sabor Chocolate ', 'snack', '23 grs', '2018-12-22', 67.86, 'maíz, azúcar, aceites y grasas vegetales, margarina, cacao en polvo, LECHE edulcorada, salsa de caramelo, sal, CREMA, LACTOSA, masa de cacao, LECHE entera en polvo, proteínas hidrolizadas, CREMA en polvo, colorante caramelo, cáscara de HUEVO, emulsionante, trehalosa (TRIGO y SOJA).', '553,9kcal • Grasas: 33,5g • Carbohidratos: 60,4g • Proteínas: 3,04g • Sal: 0,52g.', 'prd-galletaspokemon-pikachu.png', ' Nuevo y delicioso snack de trigo con sabor a chocolate. Edición Limitada personajes Pikachu.\r\n'),
('DUJML2812', 'Snack Lovely Tohato Sabor Limonada ', 'snack', '77 grs', '2019-01-24', 68.24, 'sémola de maíz, azúcar, aceite vegetal, margarina, LECHE  condensada, LACTOSA, sal, limón en polvo, sorbitol, acidulante, bicarbonato de sodio, aromas, colorante caroteno, carbonato de calcio. Contiene SOJA.\r\n', '540 kcal, Grasas: 31g, Saturadas: 0g, Carbohidratos: 63g, Azúcares: 0g, Proteínas: 2.3g & Sal: 1g\r\n', 'prd-snack-japones-caramel-corn-lemon-squash-tohato.png', 'Crujiente y dulce Snack Snack Lovely Tohato Sabor Limonada\r\nDelicioso y crujiente snack de maíz horneado con sabor a refrescante limonada.\r\n'),
('NO004224', ' Fideos Ramen Tonkotsu Receta de Kagoshima', 'ramen', '81 grs 410 ml', '2019-01-19', 84.5, 'FIDEOS FRITOS: harina de TRIGO, aceite vegetal, sal, HUEVO en polvo. SOPA:extracto de cerdo, grasa de cerdo, sal, aceite en polvo, vegetales en polvo, salsa de SOJA en polvo, aceites vegetales, extracto de pollo, azúcar, cebolla, puerro, proteínas hidrolizadas, aminoácidos, carbonato cálcico, agua kanshui, colorante (E164, E150c), vitamina E, regulador del pH, aromas, agentes aromatizantes, edulcorante (regaliz). Incluye LÁCTEOS y SÉSAMO.\r\n', '478 kcal, Grasas: 23.7g, Saturadas: 0g, Carbohidratos: 56.4g, Azúcares: 0g, Proteínas: 9.6g & Sal: 6g\r\n', 'prd-ramen-japones-tonkotsu-kagoshima.png', 'Ramen Tonkotsu elaborado según la receta de la ciudad de Kagoshima. Elaborado con carne y sopa de cerdo y pollo, salsa de soja, semillas de sésamo tostadas, cebolla, puerro asado.\r\n'),
('NO024064', 'Fideos Ramen Pikachu Seafood | Super Pocket Bowl ', 'ramen', '37 grs\r\n', '2019-01-06', 68.24, 'NOODLES: harina de TRIGO, aceite de palma, almidón, sal, hidrolizado de proteína. SOPA: azúcar, sal, extracto de pollo, extracto de MOLUSCOS, crema no láctea, extracto de carne de cerdo, almidón, proteína hidrolizada, especias, verduras, extracto de CAMARONES. TOPPINGS: pasta de PESCADOhervido, maíz, cebolletas, aminoácidos, carbonato de calcio, salmuera, aroma, espesante polisacárido, antioxidantes (Vitamina E), colorantes: gardenia y caramelo, tinta de CALAMAR, Vitamina B2, Vitamina B1, colorante Monascus, (Algunos de los ingredientes incluyen LECHE, SÉSAMO, SOJA).\r\n', '416,22 kcal • Grasas: 13,51g • Carbohidratos: 64,05g • Proteínas: 9,46g • Sal: 8,11g \r\n', 'prd-ramen-pokemon-pikachu-seafood.png', 'Ramen elaborado con caldo de polloy marisco, maíz, cebolla y narutos con divertidas caritas de Pikachu! Disfruta de este sabroso y divertido Ramen!'),
('NO338905', 'Fideos Ramen Menzukuri Miso Intenso Tonkotsu 110 grs', 'ramen', '110 grs 410 ml.', '2019-02-02', 101.17, ' FIDEOS: harina de TRIGO, sal, HUEVOen polvo, proteínas hidrolizadas. CONDIMENTOS: MISO, SÉSAMO, extracto de cerdo, pasta de SÉSAMO, azúcar, manteca de cerdo, aceite aromatizado, sal, aceite vegetal, guisantes, almidón, dextrina, extracto de especias, extracto de vegetales, productos LÁCTEOS, proteínas hidrolizadas, aditivos (bok choi, carne de pollo, puerro), almidón procesado, aminoácidos, alcohol, emulsionante, salmuera, carbonato de calcio, polisacárido espesante, colorantes (caramelo, gardenia, pimentón), extracto de especias, aromas, vitaminas (B2, B1, E).\r\n', '360 kcal, Grasas: 11.6g, Saturadas: 0g, Carbohidratos: 53.2g, Azúcares: 0g, Proteínas: 10.4g & Sal: 1g\r\n', 'prd-ramen-miso-tonkotsu-japones-maruchan.png', 'Ramen elaborado con miso intenso, carne de cerdo y pollo, aceite de sésamo, col china y cebollas verdes.\r\n'),
('NO4901990336796', 'Fideos Ramen Miso Carne y Bambú | Premium Golden', 'ramen', '111 grs 450 ml', '2018-11-18', 125.06, 'FIDEOS: harina de TRIGO,  almidón, sal, konjac, proteína vegetal, fibra dietética de la SOJA. ESPECIAS: salsa de SOJA, extracto de pollo, aceite vegetal, manteca de cerdo, extracto de carne de cerdo, condimentos fermentados, azúcar, sal, especias, extracto de PESCADO, proteína hidrolizada, extracto de levadura. CONDIMENTO: cerdo asado, puerro, brotes de bambú, algas, dextrina, almidón modificado, aderezo (aminoácidos), alcohol, lecitina, salmuera, carbonato de calcio, antioxidantes (vitamina C, vitamina E), color gardenia, polisacárido espesante, regulador de la acidez, color  caramelo, aroma, vitamina B2, vitamina B1, (HUEVO).\r\n', '333 kcal, Grasas: 10.3g, Saturadas: 6g, Carbohidratos: 49g, Azúcares: 2g, Proteínas: 11.2g & Sal: 6g\r\n', 'prd-ramen-maru-chan-sei-men-miso-bambu-japones-nissin.jpg', 'Impresionantes premium ramen elaborados con sopa y carne picada de cerdo asado, pasta de sésamo, miso intenso y brotes de bambú salteados.\r\n'),
('NO8562', '3 Raciones de Fideos Ramen Tonkotsu Frescos ', 'ramen', '618 grs 33 raciones', '2020-04-16', 152.09, 'NOODLES: agua, harina de TRIGO, aceite de germen de arroz, sal, acidulantes (ácido láctico, carbonato de sodio), especias. SOPA: SOJA, salsa de SOJA (SOJA desgrasada, TRIGO, sal, SOJA, alcohol), sal, extracto de col, mirin de especias dulces y arroz fermentado (azúcar, agua, arroz glutinoso, alcohol, arroz), azúcar, especias (ajo, jengibre, cebolla, pimienta), potenciador del sabor E635, alcohol, emulgente E471, espesante (goma xantana), colorante E150c, antioxidante E306, carbonato de sodio.\r\n', '200 kcal, Grasas: 8.4g, Saturadas: 1.1g, Carbohidratos: 26g, Azúcares: 3.1g, Proteínas: 5.4g & Sal: 8g\r\n', 'prd-fideos-ramen-tonkotsu-frescos.png', '3 Raciones de fideos ramen frescos con sopa tonkotsu, listos para tomar en solo 1 minuto.'),
('NO8564', '3 Raciones de Fideos Udon Curry Frescos', 'ramen', '642 grs 3 raciones.', '2020-04-16', 152.09, 'FIDEOS: agua, harina de TRIGO, sal, ácido láctico. SOPA: azúcar, sal,almidón de patata, vegetales en polvo (patata, calabaza, cebolla, ajo), curry en polvo (cúrcuma, cilantro, comino, fenogreco, cáscara de limón), salsa de SOJA en polvo (SOJA, TRIGO, sal, azúcar, dextrina), dextrina, harina de PESCADO, aceite de canola, cúrcuma, extracto de levadura, potenciador del sabor E621, espesante (goma guar, goma xantana), colorante (azúcar de maíz).\r\n', '127 kcal, Grasas: 0.7g, Saturadas: 0.1g, Carbohidratos: 26g, Azúcares: 3.8g, Proteínas: 3.6g & Sal: 4g\r\n', 'prd-fideos-ramen-udon-curry-frescos.png', '3 Raciones de fideos udon frescos con sopa de curry, listos para tomar en solo 1 minuto.\r\n'),
('TE6938888880114', 'Expreso Té Negro con Leche ', 'te', '300 ml.', '2019-03-13', 68.03, 'agua, LECHE concentrada, té negro, emulsionantes (E322, E471, E473), estabilizante E452, antioxidante E316, aromas.', '64 kcal, Grasas: 2.5g, Saturadas: 0g, Carbohidratos: 9.3g, Azúcares: 0g, Proteínas: 1g & Sal: 0g\r\n', 'prd-te-negro-leche-japones.jpg', 'Té negro muy fragante con leche, listo para tomar. Un desayuno y merienda ideal.\r\n'),
('TEB8809518270149', 'Té Coreano de Mermelada de Jujube ', 'te', '580 ml.', '2018-12-25', 169.5, 'extracto de jujube, rebanada de jujube, fructosa, azúcar, espesante (E407, E466), aroma a jujube, agua, glucosa.\r\n', '144kcal • Grasas: 0g - Saturadas: 0g  • Carbohidratos: 35,7g - Azúcares: 28,9g • Proteínas: 0g • Sal: 0,03g.', 'prd-te-coreano-yuja-cha.png', 'Té coreano de mermelada de Jujube. Elaboración tradicional.\r\n'),
('TEJFJ1009', 'Té Verde Sencha en Infusión', 'te', '32 grs. 16 bolsitas.\r\n', '2019-10-10', 126.95, 'Té verde (Camellia Sinesis).', '0 kcal, Grasas: 0g, Saturadas: 0g, Carbohidratos: 0g, Azúcares: 0g, Proteínas: 0g & Sal: 0g\r\nImagen: \r\n', 't-sencha-japons-infusin.png', 'Te verde japonés en bolsitas, rápido y muy cómodo de preparar.\r\nEl te verde japonés Sencha se elabora de una forma artesanal exponiendo sus hojas al sol. Sus cualidades medicinales son muy conocidas, es beneficioso para la piel, facilita la digestión previene la fatiga y es muy refrescante.\r\n');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `users`
--

CREATE TABLE `users` (
  `id` int(7) NOT NULL,
  `password` varchar(50) NOT NULL,
  `username` varchar(50) NOT NULL,
  `email` varchar(70) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `users`
--

INSERT INTO `users` (`id`, `password`, `username`, `email`) VALUES
(1, 'usagii19', 'UsagiiHaku', 'usagiihaku@gmail.com'),
(2, 'teamosheila', 'Migdonio1', 'raulmigdonio@gmail.com'),
(3, 'soynegro', 'emilio', 'emiliobalderas@gmail.com'),
(4, 'soynegro', 'sheila', 'sheilaricaldeperez@gmail.com');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`SKU`);

--
-- Indices de la tabla `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `users`
--
ALTER TABLE `users`
  MODIFY `id` int(7) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
